### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/charles-ai#7]
- [x] Basic Discord Interface for Chat API
- [x] Blog Part 1 (Basic Discord Interface for Chat API
- [x] Plugin API with Weather and Time Test Plugins
- [ ] Blog Part 2 (Plugin API)
- [ ] Expand List of Available Plugins - Looking For Suggestions
- [ ] Explore Other AI Models
- [ ] Blog Part 3 (Exploring Other AI Models)
